# -*- coding: utf-8 -*-
"""
/***************************************************************************
 THW
                                 A QGIS plugin
 Tools for supporting THW 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-02-19
        copyright            : (C) 2022 by Christina Ludwig (THW Heidelberg)
        email                : christina.ludwig@thw-heidelberg.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Christina Ludwig (THW Heidelberg)'
__date__ = '2022-02-19'
__copyright__ = '(C) 2022 by Christina Ludwig (THW Heidelberg)'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load THW class from file THW.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .thw import THWPlugin
    return THWPlugin()
